/**
 * Seeds the database with fictional demonstration data:
 * - the "Boreal Hockey League" (BHL), 4 seasons of versioned rules
 * - 4 organizations, one team each, ~120 fictional players, 100+ contracts
 * - retained salary, dead cap, IR/LTIR, two-way deals, buried contracts
 * - 5 saved scenarios, 20 official transaction examples
 * - projections, comparable contracts, persisted valuations
 * - demo logins (see console output at the end)
 *
 * All people, teams, and figures are fictional. Deterministic RNG so reseeds
 * are reproducible.
 */
import path from "path";
import fs from "fs";
import { eq } from "drizzle-orm";
import {
  calculateSurplusValue,
  estimateMarketValue,
  estimatePerformanceValue,
  MARKET_MODEL_VERSION,
  PERFORMANCE_MODEL_VERSION,
} from "../src/lib/valuation/models";
import { hashPassword } from "../src/lib/auth/password";
import * as schema from "../src/db/schema";
import { seedScouting } from "./seedScouting";

/* ---------------- deterministic RNG ---------------- */
function mulberry32(seed: number) {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(20260718);
const pick = <T,>(arr: T[]): T => {
  const v = arr[Math.floor(rand() * arr.length)];
  if (v === undefined) throw new Error("empty pick");
  return v;
};
const randInt = (lo: number, hi: number) => lo + Math.floor(rand() * (hi - lo + 1));
const round25k = (n: number) => Math.round(n / 25_000) * 25_000;

const FIRST = ["Anders","Bram","Caleb","Dmitri","Emil","Foster","Grady","Henrik","Ivan","Jonas","Kasper","Levi","Matteo","Nils","Oskar","Pavel","Quinn","Rasmus","Soren","Tobias","Ulrik","Viktor","Wade","Xavier","Yannick","Zane","Arlo","Bennett","Corey","Dawson","Elias","Finn","Gunnar","Holt","Ilya","Jarek","Kellan","Lucas","Miles","Nolan"];
const LAST = ["Aalto","Bergstrom","Calloway","Drexler","Eklund","Falk","Grimsby","Halloran","Ivarsson","Jokinen","Kovac","Lindqvist","Marek","Nyström","Ostrander","Pekkala","Quist","Rantala","Sorvali","Tikkanen","Ullmark","Voss","Wexford","Yaeger","Zetterlund","Ashford","Blackwood","Corrigan","Dunmore","Ellery","Farrow","Granlund","Holmberg","Isaksen","Jarnefelt","Kettering","Lammers","Mortensen","Novak","Oberg","Paulsen","Renfrew","Stavros","Thorne","Vance","Wickham","Ylitalo","Zeller"];
const NATIONS = ["Canada","United States","Sweden","Finland","Czechia","Slovakia","Germany","Switzerland","Latvia","Denmark"];

const usedNames = new Set<string>();
function fictionalName(): string {
  for (let i = 0; i < 200; i++) {
    const name = `${pick(FIRST)} ${pick(LAST)}`;
    if (!usedNames.has(name)) {
      usedNames.add(name);
      return name;
    }
  }
  const fallback = `${pick(FIRST)} ${pick(LAST)} ${usedNames.size}`;
  usedNames.add(fallback);
  return fallback;
}

async function main() {
  // Connect (same logic as src/db/client.ts, without server-only)
  // Connect to local PGlite only (remote seeding is disabled below).

  if (process.env.DATABASE_URL) {
    throw new Error("Seeding a remote database is intentionally disabled. Unset DATABASE_URL to seed the local demo database.");
  }
  const { drizzle } = await import("drizzle-orm/pglite");
  const { PGlite } = await import("@electric-sql/pglite");
  const dataDir = process.env.PGLITE_DATA_DIR ?? path.join(process.cwd(), ".data", "pglite");
  fs.mkdirSync(path.dirname(dataDir), { recursive: true });
  const pglite = new PGlite(dataDir);
  const db = drizzle(pglite, { schema });
  const close = () => pglite.close();

  const existing = await db.select().from(schema.leagues).limit(1);
  if (existing.length > 0) {
    console.log("Database already seeded — run `npm run db:reset` to reseed from scratch.");
    await close();
    return;
  }

  /* ---------------- data source ---------------- */
  const [seedSource] = await db
    .insert(schema.dataSources)
    .values({
      name: "RosterIQ demonstration seed",
      notes: "Fictional data generated by scripts/seed.ts. Not real players, teams, or contracts.",
      confidence: 1,
    })
    .returning();
  if (!seedSource) throw new Error("seed source insert failed");

  /* ---------------- league & seasons ---------------- */
  const [league] = await db
    .insert(schema.leagues)
    .values({
      name: "Boreal Hockey League",
      abbreviation: "BHL",
      sport: "hockey",
      level: "professional",
      capSystem: "annual_hard_cap",
    })
    .returning();
  if (!league) throw new Error("league insert failed");

  const seasonDefs = [
    { name: "2025-26", start: "2025-10-07", end: "2026-06-20", cap: 88_000_000, floor: 65_000_000, min: 800_000, current: true },
    { name: "2026-27", start: "2026-10-06", end: "2027-06-19", cap: 92_500_000, floor: 68_500_000, min: 825_000, current: false },
    { name: "2027-28", start: "2027-10-05", end: "2028-06-17", cap: 96_500_000, floor: 71_500_000, min: 850_000, current: false },
    { name: "2028-29", start: "2028-10-03", end: "2029-06-16", cap: 100_500_000, floor: 74_500_000, min: 875_000, current: false },
  ];

  const seasons: Array<typeof schema.leagueSeasons.$inferSelect> = [];
  for (let i = 0; i < seasonDefs.length; i++) {
    const def = seasonDefs[i]!;
    const [season] = await db
      .insert(schema.leagueSeasons)
      .values({
        leagueId: league.id,
        name: def.name,
        startDate: def.start,
        endDate: def.end,
        tradeDeadline: `${def.start.slice(0, 4) === "2025" ? "2026" : String(Number(def.start.slice(0, 4)) + 1)}-03-05`,
        isCurrent: def.current,
        sortOrder: i,
      })
      .returning();
    if (!season) throw new Error("season insert failed");
    seasons.push(season);

    const rules: Array<{ key: string; name: string; category: string; value: number }> = [
      { key: "cap.upper_limit", name: "Salary cap upper limit", category: "cap", value: def.cap },
      { key: "cap.lower_limit", name: "Salary cap lower limit (floor)", category: "cap", value: def.floor },
      { key: "cap.buried_allowance", name: "Buried-contract cap relief allowance", category: "cap", value: 1_150_000 },
      { key: "roster.max_active", name: "Maximum active roster size", category: "roster", value: 23 },
      { key: "roster.min_active", name: "Minimum active roster size", category: "roster", value: 20 },
      { key: "roster.min_goalies", name: "Minimum goaltenders on active roster", category: "roster", value: 2 },
      { key: "contract.max_slots", name: "Maximum contracts per organization", category: "contract", value: 50 },
      { key: "salary.min", name: "League minimum salary", category: "salary", value: def.min },
      { key: "salary.max_individual_pct", name: "Maximum individual cap hit (% of upper limit)", category: "salary", value: 20 },
      { key: "waiver.exempt_games", name: "Waiver exemption threshold (pro games)", category: "waiver", value: 160 },
    ];
    for (const r of rules) {
      await db.insert(schema.leagueRules).values({
        leagueId: league.id,
        seasonId: season.id,
        ruleKey: r.key,
        ruleName: r.name,
        ruleCategory: r.category,
        numericValue: r.value,
        effectiveDate: def.start,
        sourceId: seedSource.id,
        ruleVersion: 1,
        isActive: true,
        notes: "Fictional BHL parameter for demonstration.",
      });
    }
    await db.insert(schema.salaryCapPeriods).values({
      leagueId: league.id,
      seasonId: season.id,
      periodType: "season",
      periodStart: def.start,
      periodEnd: def.end,
      upperLimit: def.cap,
      lowerLimit: def.floor,
    });
    await db.insert(schema.rosterLimits).values([
      { leagueId: league.id, seasonId: season.id, limitKey: "max_active", limitValue: 23 },
      { leagueId: league.id, seasonId: season.id, limitKey: "min_active", limitValue: 20 },
      { leagueId: league.id, seasonId: season.id, limitKey: "max_contracts", limitValue: 50 },
    ]);
  }
  const s0 = seasons[0]!;
  const s1 = seasons[1]!;

  /* ---------------- users & organizations ---------------- */
  const demoPassword = "rosteriq-demo";
  const [gmUser] = await db
    .insert(schema.users)
    .values({
      email: "gm@aurora.demo",
      passwordHash: hashPassword(demoPassword),
      fullName: "Demo General Manager",
    })
    .returning();
  const [analystUser] = await db
    .insert(schema.users)
    .values({
      email: "analyst@aurora.demo",
      passwordHash: hashPassword(demoPassword),
      fullName: "Demo Cap Analyst",
    })
    .returning();
  const [rivalUser] = await db
    .insert(schema.users)
    .values({
      email: "gm@ironport.demo",
      passwordHash: hashPassword(demoPassword),
      fullName: "Rival General Manager",
    })
    .returning();
  if (!gmUser || !analystUser || !rivalUser) throw new Error("user insert failed");

  const teamDefs = [
    { org: "Aurora Ridge Hockey Club", slug: "aurora-ridge", team: "Aurora Wolfpack", abbr: "AUR", city: "Aurora Ridge", targetSpend: 0.87 },
    { org: "Ironport Athletic Company", slug: "ironport", team: "Ironport Admirals", abbr: "IRP", city: "Ironport", targetSpend: 0.84 },
    { org: "Redstone Hockey Group", slug: "redstone", team: "Redstone Miners", abbr: "RDS", city: "Redstone", targetSpend: 1.02 }, // intentionally over the cap → seeded compliance violation
    { org: "Harborview Sports Trust", slug: "harborview", team: "Harborview Sentinels", abbr: "HRB", city: "Harborview", targetSpend: 0.63 }, // below the salary floor → seeded warning
  ];

  const orgs: Array<typeof schema.organizations.$inferSelect> = [];
  const teams: Array<typeof schema.teams.$inferSelect> = [];
  for (const def of teamDefs) {
    const [org] = await db
      .insert(schema.organizations)
      .values({ name: def.org, slug: def.slug, orgType: "pro_team", createdBy: gmUser.id })
      .returning();
    if (!org) throw new Error("org insert failed");
    orgs.push(org);
    const [team] = await db
      .insert(schema.teams)
      .values({
        organizationId: org.id,
        leagueId: league.id,
        name: def.team,
        abbreviation: def.abbr,
        city: def.city,
        level: "pro",
      })
      .returning();
    if (!team) throw new Error("team insert failed");
    teams.push(team);
  }
  const auroraOrg = orgs[0]!;
  const ironportOrg = orgs[1]!;

  await db.insert(schema.organizationMembers).values([
    { organizationId: auroraOrg.id, userId: gmUser.id, role: "org_admin" },
    { organizationId: auroraOrg.id, userId: analystUser.id, role: "cap_analyst" },
    { organizationId: ironportOrg.id, userId: rivalUser.id, role: "general_manager" },
  ]);

  /* ---------------- players & contracts ---------------- */

  const playersByTeam = new Map<string, Array<typeof schema.players.$inferSelect>>();
  const contractsByTeam = new Map<string, Array<{ contract: typeof schema.contracts.$inferSelect; capHits: number[]; firstSeason: number; term: number }>>();

  for (let t = 0; t < teams.length; t++) {
    const team = teams[t]!;
    const org = orgs[t]!;
    const spendScale = teamDefs[t]!.targetSpend;

    // 23 active (13F/8D/2G), 5 minors (two-way), 2 IR-ish handled below
    const activeSlots: Array<{ pos: string; tier: "star" | "top" | "mid" | "depth" }> = [];
    const fPos = ["C", "C", "C", "C", "LW", "LW", "LW", "RW", "RW", "RW", "C", "LW", "RW"];
    const dPos = ["D", "D", "D", "D", "D", "D", "D", "D"];
    fPos.forEach((pos, i) => activeSlots.push({ pos, tier: i < 2 ? "star" : i < 5 ? "top" : i < 9 ? "mid" : "depth" }));
    dPos.forEach((pos, i) => activeSlots.push({ pos, tier: i < 1 ? "star" : i < 3 ? "top" : i < 6 ? "mid" : "depth" }));
    activeSlots.push({ pos: "G", tier: "top" }, { pos: "G", tier: "depth" });

    const tierRange: Record<string, [number, number]> = {
      star: [7_500_000, 10_500_000],
      top: [4_750_000, 7_250_000],
      mid: [2_250_000, 4_500_000],
      depth: [800_000, 2_000_000],
    };

    const teamPlayers: Array<typeof schema.players.$inferSelect> = [];
    const teamContracts: NonNullable<ReturnType<typeof contractsByTeam.get>> = [];

    const insertPlayerWithContract = async (opts: {
      pos: string;
      capHit: number;
      status: (typeof schema.rosterStatus.enumValues)[number];
      twoWay: boolean;
      term: number;
      age: number;
      games: number;
    }) => {
      const dobYear = 2026 - opts.age;
      const [player] = await db
        .insert(schema.players)
        .values({
          organizationId: org.id,
          fullName: fictionalName(),
          position: opts.pos,
          shootsCatches: rand() < 0.6 ? "L" : "R",
          dateOfBirth: `${dobYear}-${String(randInt(1, 12)).padStart(2, "0")}-${String(randInt(1, 28)).padStart(2, "0")}`,
          heightCm: randInt(175, 200),
          weightKg: randInt(78, 105),
          nationality: pick(NATIONS),
          draftYear: dobYear + 18,
          draftRound: randInt(1, 7),
          draftOverall: randInt(1, 224),
          currentTeamId: team.id,
          rosterStatus: opts.status,
          freeAgentStatus: "under_contract",
          waiverStatus: opts.games < 160 ? "exempt" : "required",
          proGamesPlayed: opts.games,
          injuryStatus: opts.status === "injured_reserve" ? "Lower body — week to week" : opts.status === "ltir" ? "Shoulder — out long term" : null,
          sourceId: seedSource.id,
          provenance: "user_entered",
        })
        .returning();
      if (!player) throw new Error("player insert failed");
      teamPlayers.push(player);

      const term = opts.term;
      const start = seasons[0]!;
      const end = seasons[Math.min(term - 1, seasons.length - 1)]!;
      const retainedPct = 0;
      const [contract] = await db
        .insert(schema.contracts)
        .values({
          organizationId: org.id,
          playerId: player.id,
          teamId: team.id,
          leagueId: league.id,
          contractType: opts.twoWay ? "two_way" : opts.age <= 22 ? "entry_level" : "one_way",
          contractStatus: "active",
          signedDate: "2025-07-01",
          startDate: start.startDate,
          endDate: end.endDate,
          totalValue: opts.capHit * term,
          averageAnnualValue: opts.capHit,
          guaranteedValue: Math.round(opts.capHit * term * (opts.twoWay ? 0.3 : 0.9)),
          minorLeagueValue: opts.twoWay ? round25k(90_000 + rand() * 60_000) : null,
          signingBonusTotal: rand() < 0.3 ? round25k(opts.capHit * 0.15) : 0,
          performanceBonusTotal: opts.age <= 22 ? round25k(opts.capHit * 0.1) : 0,
          noTradeClause: opts.capHit > 7_000_000 && rand() < 0.6,
          noMovementClause: opts.capHit > 9_000_000 && rand() < 0.5,
          retainedSalaryPercentage: retainedPct,
          arbitrationStatus: opts.age >= 23 && opts.age <= 26 ? "eligible" : "ineligible",
          freeAgentStatus: "under_contract",
          waiverStatus: opts.games < 160 ? "exempt" : "required",
          sourceId: seedSource.id,
          provenance: "user_entered",
          verificationStatus: "verified",
          lastVerifiedAt: new Date(),
          createdBy: gmUser.id,
        })
        .returning();
      if (!contract) throw new Error("contract insert failed");

      const capHits: number[] = [];
      for (let y = 0; y < term && y < seasons.length; y++) {
        const season = seasons[y]!;
        const base = round25k(opts.capHit * (0.9 + rand() * 0.2));
        const perfBonus = opts.age <= 22 && y === 0 ? round25k(opts.capHit * 0.1) : 0;
        await db.insert(schema.contractSeasons).values({
          contractId: contract.id,
          seasonId: season.id,
          baseSalary: base,
          signingBonus: 0,
          performanceBonus: perfBonus,
          totalCash: base + perfBonus,
          capHit: opts.capHit,
          minorLeagueSalary: contract.minorLeagueValue,
          retainedSalary: 0,
        });
        capHits.push(opts.capHit);
      }
      teamContracts.push({ contract, capHits, firstSeason: 0, term });
      return { player, contract };
    };

    for (const slot of activeSlots) {
      const [lo, hi] = tierRange[slot.tier]!;
      const capHit = round25k((lo + rand() * (hi - lo)) * spendScale);
      const age = slot.tier === "star" ? randInt(24, 32) : slot.tier === "depth" ? randInt(21, 34) : randInt(22, 34);
      await insertPlayerWithContract({
        pos: slot.pos,
        capHit: Math.max(seasonDefs[0]!.min, capHit),
        status: "pro_active",
        twoWay: false,
        term: randInt(1, 4),
        age,
        games: age <= 22 ? randInt(0, 150) : randInt(160, 900),
      });
    }

    // Injured players: 1 IR + 1 LTIR per team (moved off active count)
    const ir = teamPlayers[2]!;
    await db.update(schema.players).set({ rosterStatus: "injured_reserve", injuryStatus: "Lower body — week to week" }).where(eq(schema.players.id, ir.id));
    ir.rosterStatus = "injured_reserve";
    if (t % 2 === 0) {
      const ltir = teamPlayers[5]!;
      await db.update(schema.players).set({ rosterStatus: "ltir", injuryStatus: "Shoulder — out long term" }).where(eq(schema.players.id, ltir.id));
      ltir.rosterStatus = "ltir";
    }

    // Minor-league group: 4 cheap two-ways + 1 buried one-way
    for (let m = 0; m < 4; m++) {
      await insertPlayerWithContract({
        pos: pick(["C", "LW", "RW", "D", "G"]),
        capHit: round25k(825_000 + rand() * 150_000),
        status: "minor",
        twoWay: true,
        term: randInt(1, 3),
        age: randInt(20, 25),
        games: randInt(0, 100),
      });
    }
    await insertPlayerWithContract({
      pos: "LW",
      capHit: 2_750_000, // buried: charge above threshold
      status: "minor",
      twoWay: false,
      term: 2,
      age: 30,
      games: 500,
    });

    // Retained salary + dead cap obligations
    await db.insert(schema.capObligations).values([
      {
        organizationId: org.id,
        teamId: team.id,
        seasonId: s0.id,
        obligationType: "retained",
        playerName: fictionalName(),
        amount: round25k(900_000 + rand() * 1_600_000),
        notes: "50% retained in a prior fictional trade.",
      },
      {
        organizationId: org.id,
        teamId: team.id,
        seasonId: s0.id,
        obligationType: "buyout",
        playerName: fictionalName(),
        amount: round25k(500_000 + rand() * 1_200_000),
        notes: "Year 1 of fictional buyout schedule.",
      },
      {
        organizationId: org.id,
        teamId: team.id,
        seasonId: s1.id,
        obligationType: "buyout",
        playerName: "(same buyout, year 2)",
        amount: round25k(400_000 + rand() * 900_000),
      },
    ]);

    // Official roster containers
    for (const season of seasons.slice(0, 2)) {
      const [roster] = await db
        .insert(schema.rosters)
        .values({ teamId: team.id, seasonId: season.id, name: "Official", isOfficial: true })
        .returning();
      if (roster) {
        await db.insert(schema.rosterMemberships).values(
          teamPlayers.map((p) => ({ rosterId: roster.id, playerId: p.id, status: p.rosterStatus })),
        );
      }
    }

    playersByTeam.set(team.id, teamPlayers);
    contractsByTeam.set(team.id, teamContracts);
  }

  /* ---------------- free agents (Aurora scouting pool) ---------------- */
  const freeAgents: Array<typeof schema.players.$inferSelect> = [];
  for (let i = 0; i < 8; i++) {
    const age = randInt(22, 34);
    const [fa] = await db
      .insert(schema.players)
      .values({
        organizationId: auroraOrg.id,
        fullName: fictionalName(),
        position: pick(["C", "LW", "RW", "D", "G"]),
        dateOfBirth: `${2026 - age}-${String(randInt(1, 12)).padStart(2, "0")}-15`,
        nationality: pick(NATIONS),
        currentTeamId: null,
        rosterStatus: "non_roster",
        freeAgentStatus: age <= 25 ? "rfa" : "ufa",
        waiverStatus: "required",
        proGamesPlayed: randInt(100, 800),
        notes: "Free-agent target tracked by scouting staff.",
        sourceId: seedSource.id,
        provenance: "user_entered",
      })
      .returning();
    if (fa) freeAgents.push(fa);
  }

  /* ---------------- projections ---------------- */
  const allPlayers = [...playersByTeam.values()].flat().concat(freeAgents);
  const capHitByPlayer = new Map<string, number>();
  for (const list of contractsByTeam.values()) {
    for (const { contract, capHits } of list) {
      capHitByPlayer.set(contract.playerId, capHits[0] ?? 0);
    }
  }

  for (const p of allPlayers) {
    const hit = capHitByPlayer.get(p.id) ?? round25k(1_000_000 + rand() * 4_000_000);
    // GAR loosely tracks pay with noise so surplus spreads both ways.
    const gar = Math.max(-3, (hit / 1_000_000) * 1.35 + (rand() - 0.5) * 7);
    const points =
      p.position === "G" ? 0 : Math.max(2, Math.round((hit / 1_000_000) * 8 + (rand() - 0.5) * 22));
    for (const season of seasons.slice(0, 2)) {
      await db.insert(schema.playerProjections).values({
        playerId: p.id,
        seasonId: season.id,
        modelVersion: PERFORMANCE_MODEL_VERSION,
        projectedGamesPlayed: randInt(55, 82),
        projectedGoals: Math.round(points * 0.4),
        projectedAssists: Math.round(points * 0.6),
        projectedPoints: points,
        projectedTimeOnIce: p.position === "D" ? 18 + rand() * 6 : 12 + rand() * 8,
        projectedGar: Number(gar.toFixed(1)),
        projectedWar: Number((gar / 6).toFixed(2)),
        projectedAvailability: Number((0.82 + rand() * 0.18).toFixed(2)),
        provenance: "projected",
      });
    }
    await db.insert(schema.playerStatistics).values({
      playerId: p.id,
      seasonId: s0.id,
      leagueId: league.id,
      gamesPlayed: randInt(40, 82),
      goals: Math.round(points * 0.38),
      assists: Math.round(points * 0.58),
      points: Math.round(points * 0.96),
      timeOnIceMinutes: 60 * randInt(500, 1500),
      goalsAboveReplacement: Number((gar * (0.8 + rand() * 0.4)).toFixed(1)),
      winsAboveReplacement: Number((gar / 6).toFixed(2)),
      expectedGoalsImpact: Number(((rand() - 0.4) * 10).toFixed(1)),
      defensiveImpact: Number(((rand() - 0.5) * 8).toFixed(1)),
      provenance: "estimated",
      sourceId: seedSource.id,
    });
  }

  /* ---------------- comparable contracts (global pool) ---------------- */
  for (let i = 0; i < 60; i++) {
    const position = pick(["C", "C", "LW", "RW", "D", "D", "G"]);
    const points = position === "G" ? 0 : randInt(10, 95);
    const aav = round25k(
      Math.max(800_000, position === "G" ? 1_000_000 + rand() * 7_500_000 : 900_000 + points * 95_000 * (0.75 + rand() * 0.5)),
    );
    await db.insert(schema.comparableContracts).values({
      organizationId: null,
      playerName: fictionalName(),
      position,
      ageAtSigning: randInt(21, 34),
      platformPoints: points,
      platformGar: Number(((aav / 1_000_000) * 1.3 + (rand() - 0.5) * 5).toFixed(1)),
      aav,
      termYears: randInt(1, 8),
      signingSeason: pick(["2023-24", "2024-25", "2025-26"]),
      capPctAtSigning: Number(((aav / 84_000_000) * 100).toFixed(2)),
      provenance: "estimated",
      sourceId: seedSource.id,
    });
  }

  /* ---------------- persisted valuations for Aurora ---------------- */
  const comparables = await db.select().from(schema.comparableContracts);
  const auroraTeam = teams[0]!;
  const auroraPlayers = playersByTeam.get(auroraTeam.id) ?? [];
  const minSalary = seasonDefs[0]!.min;
  for (const p of [...auroraPlayers, ...freeAgents]) {
    const projRows = await db
      .select()
      .from(schema.playerProjections)
      .where(eq(schema.playerProjections.playerId, p.id));
    const proj = projRows.find((r) => r.seasonId === s0.id);
    if (!proj) continue;
    const age = p.dateOfBirth ? 2025 - Number(p.dateOfBirth.slice(0, 4)) : null;
    const perf = estimatePerformanceValue({
      projectedGar: proj.projectedGar,
      projectedAvailability: proj.projectedAvailability,
      position: p.position,
      age,
      leagueMinSalary: minSalary,
      dollarsPerGar: 425_000,
    });
    const market = estimateMarketValue({
      playerName: p.fullName,
      position: p.position,
      age,
      platformPoints: proj.projectedPoints,
      performanceValue: perf.performanceValue,
      freeAgentStatus: p.freeAgentStatus,
      comparables: comparables.map((c) => ({
        id: c.id, playerName: c.playerName, position: c.position, ageAtSigning: c.ageAtSigning,
        platformPoints: c.platformPoints, aav: c.aav, termYears: c.termYears, signingSeason: c.signingSeason,
      })),
      capInflationPct: 0.04,
      leagueMinSalary: minSalary,
    });
    await db.insert(schema.playerValuations).values({
      playerId: p.id,
      seasonId: s0.id,
      modelVersion: MARKET_MODEL_VERSION,
      estimatedAav: market.estimatedAav,
      estimatedAavLow: market.lowEstimate,
      estimatedAavHigh: market.highEstimate,
      estimatedTermYears: market.estimatedTermYears,
      estimatedTotalValue: market.estimatedTotalValue,
      performanceValue: perf.performanceValue,
      confidence: market.confidence,
      assumptions: { list: market.assumptions },
      inputDataDate: "2025-07-01",
    });
    const hit = capHitByPlayer.get(p.id);
    if (hit !== undefined) {
      const contractRow = contractsByTeam.get(auroraTeam.id)?.find((c) => c.contract.playerId === p.id);
      const surplus = calculateSurplusValue(perf.performanceValue, hit);
      await db.insert(schema.surplusValueRecords).values({
        playerId: p.id,
        contractId: contractRow?.contract.id ?? null,
        seasonId: s0.id,
        modelVersion: PERFORMANCE_MODEL_VERSION,
        performanceValue: surplus.performanceValue,
        capHit: surplus.capHit,
        surplusValue: surplus.surplusValue,
      });
    }
  }

  /* ---------------- scenarios (Aurora) ---------------- */
  const auroraContracts = contractsByTeam.get(auroraTeam.id) ?? [];
  const starContract = auroraContracts.reduce((a, b) => ((a.capHits[0] ?? 0) > (b.capHits[0] ?? 0) ? a : b));
  const midContract = auroraContracts.find((c) => (c.capHits[0] ?? 0) > 2_000_000 && (c.capHits[0] ?? 0) < 5_000_000) ?? auroraContracts[5]!;
  const depthContract = auroraContracts.find((c) => (c.capHits[0] ?? 0) <= 2_000_000) ?? auroraContracts[10]!;
  const minorContract = auroraContracts[auroraContracts.length - 2]!;
  const faTarget = freeAgents[0]!;

  const mkScenario = async (
    name: string,
    description: string,
    status: (typeof schema.scenarioStatus.enumValues)[number],
    txs: Array<{ label: string; type: (typeof schema.transactionType.enumValues)[number]; payload: unknown; notes?: string }>,
  ) => {
    const [scenario] = await db
      .insert(schema.scenarios)
      .values({
        organizationId: auroraOrg.id,
        teamId: auroraTeam.id,
        name,
        description,
        baseSeasonId: s0.id,
        status,
        createdBy: gmUser.id,
      })
      .returning();
    if (!scenario) throw new Error("scenario insert failed");
    for (let i = 0; i < txs.length; i++) {
      const tx = txs[i]!;
      await db.insert(schema.scenarioTransactions).values({
        scenarioId: scenario.id,
        sortOrder: i,
        transactionType: tx.type,
        label: tx.label,
        payload: tx.payload,
        notes: tx.notes,
      });
    }
    await db.insert(schema.auditLogs).values({
      organizationId: auroraOrg.id,
      userId: gmUser.id,
      action: "scenario.create",
      entityType: "scenario",
      entityId: scenario.id,
      newValues: { name },
    });
    return scenario;
  };

  await mkScenario(
    "Deadline: add a top-six scorer",
    "Acquire a fictional scoring winger at 50% retained, moving out a middle-six contract.",
    "active",
    [
      {
        label: `Trade out ${midContract.contract.id.slice(0, 8)}`,
        type: "trade",
        payload: { kind: "trade_out", contractId: midContract.contract.id, retainedPct: 0.25, tradePartner: "Redstone Miners" },
      },
      {
        label: "Trade in scoring winger (50% retained)",
        type: "trade",
        payload: {
          kind: "trade_in",
          playerName: "Target Winger (fictional)",
          position: "RW",
          retainedByOthersPct: 0.5,
          seasons: [
            { seasonName: "2025-26", capHit: 7_000_000 },
            { seasonName: "2026-27", capHit: 7_000_000 },
          ],
          tradePartner: "Redstone Miners",
        },
      },
    ],
  );

  await mkScenario(
    `Sign UFA ${faTarget.fullName}`,
    "Three-year deal for the top scouted free agent at the model's median estimate.",
    "active",
    [
      {
        label: `Sign ${faTarget.fullName} (3 × $5.5M)`,
        type: "sign_free_agent",
        payload: {
          kind: "sign_free_agent",
          playerName: faTarget.fullName,
          position: faTarget.position,
          isTwoWay: false,
          seasons: [
            { seasonName: "2025-26", capHit: 5_500_000 },
            { seasonName: "2026-27", capHit: 5_500_000 },
            { seasonName: "2027-28", capHit: 5_500_000 },
          ],
        },
      },
    ],
  );

  await mkScenario(
    "Overspend stress test",
    "Deliberately exceeds the upper limit to demonstrate blocking violations.",
    "draft",
    [
      {
        label: "Sign fictional star center (1 × $14M)",
        type: "sign_free_agent",
        payload: {
          kind: "sign_free_agent",
          playerName: "Max Contract Test",
          position: "C",
          isTwoWay: false,
          seasons: [{ seasonName: "2025-26", capHit: 14_000_000 }],
        },
      },
    ],
  );

  await mkScenario(
    "Cap relief: bury and recall",
    "Send a depth contract to the minors and recall a two-way forward.",
    "draft",
    [
      { label: "Send down depth player", type: "send_down", payload: { kind: "send_down", contractId: depthContract.contract.id } },
      { label: "Recall two-way forward", type: "call_up", payload: { kind: "call_up", contractId: minorContract.contract.id } },
    ],
  );

  await mkScenario(
    "Extend the franchise player",
    "Two added years at a raise, starting when the current deal ends.",
    "archived",
    [
      {
        label: "Extension: 2 × $9.5M",
        type: "extension",
        payload: {
          kind: "extension",
          contractId: starContract.contract.id,
          seasons: [
            { seasonName: "2027-28", capHit: 9_500_000 },
            { seasonName: "2028-29", capHit: 9_500_000 },
          ],
        },
      },
    ],
  );

  /* ---------------- official transaction examples ---------------- */
  const txTypes: Array<(typeof schema.transactionType.enumValues)[number]> = [
    "call_up", "send_down", "ir_placement", "trade", "sign_free_agent",
  ];
  for (let i = 0; i < 20; i++) {
    const team = teams[i % teams.length]!;
    const org = orgs[i % orgs.length]!;
    const teamPlayers = playersByTeam.get(team.id) ?? [];
    const p = teamPlayers[randInt(0, teamPlayers.length - 1)]!;
    const type = txTypes[i % txTypes.length]!;
    const [txRow] = await db
      .insert(schema.transactions)
      .values({
        organizationId: org.id,
        teamId: team.id,
        seasonId: s0.id,
        transactionType: type,
        transactionDate: `2025-${String(randInt(10, 12)).padStart(2, "0")}-${String(randInt(1, 28)).padStart(2, "0")}`,
        description: `${type.replace(/_/g, " ")} — ${p.fullName} (seeded example)`,
        isOfficial: true,
        payload: { example: true },
        createdBy: gmUser.id,
      })
      .returning();
    if (txRow) {
      await db.insert(schema.transactionItems).values({
        transactionId: txRow.id,
        playerId: p.id,
        itemType: "player_out",
        details: { note: "seeded example item" },
      });
    }
  }

  await db.insert(schema.auditLogs).values({
    organizationId: null,
    userId: null,
    action: "seed.run",
    entityType: "database",
    newValues: { players: allPlayers.length, teams: teams.length },
    reason: "Demonstration seed",
  });

  /* ---------------- amateur scouting module ---------------- */
  const [scoutingDirector] = await db
    .insert(schema.users)
    .values({
      email: "scouting@aurora.demo",
      passwordHash: hashPassword(demoPassword),
      fullName: "Demo Scouting Director",
    })
    .returning();
  if (scoutingDirector) {
    await db.insert(schema.organizationMembers).values({
      organizationId: auroraOrg.id,
      userId: scoutingDirector.id,
      role: "scouting_director",
    });
  }
  const scouting = await seedScouting(db, {
    auroraOrgId: auroraOrg.id,
    ironportOrgId: ironportOrg.id,
    gmUserId: gmUser.id,
    analystUserId: analystUser.id,
    rightsHolderNames: teams.map((t) => t.name),
  });
  console.log(`  Scouting: ${scouting.prospects} NCAA prospects seeded`);

  console.log("Seed complete.");
  console.log(`  Players: ${allPlayers.length}, Teams: ${teams.length}, Seasons: ${seasons.length}`);
  console.log("  Demo logins (password: rosteriq-demo):");
  console.log("    gm@aurora.demo       — org admin, Aurora Ridge Hockey Club");
  console.log("    analyst@aurora.demo  — cap analyst, Aurora Ridge Hockey Club");
  console.log("    gm@ironport.demo     — GM, Ironport Athletic Company (isolation demo)");
  await close();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
